Issue #15 and improvements
ramnasidharta/graphical-recipe pull request #23
Opened 2019-04-05 02:48 UTC by ramnasidharta

Closes #15 
Fixes, avoiding errors, and some improvements

2019-04-06 20:34 UTC, FabioMoreiraFM commented on src/controller.hpp
> +	try {
spacing problem

2019-04-06 20:51 UTC, FabioMoreiraFM requested changes
The system isn't cleaning correctly the polygon coordinate list. The first time you insert the coordinates, if you insert less than 3 coordinates, the system don't allow. But if you insert correctly one polygon and after that erase one or more coordinates, you can draw a new "polygon" with less than 3 coordinates. If you try to remove this "polygon", the system breaks.

The system isn't drawing the right figure. For instance (100, 5) (200, 5) (200, 100) (100, 100) is supposed to draw a square, but it is drawed a triangle.

Some parts of the code are with spacing problems (I pointed out with comments.)

2019-04-06 20:51 UTC, FabioMoreiraFM commented on src/logger.hpp
> +	GtkTextIter iter;
Spacing problem

2019-04-06 22:55 UTC, ramnasidharta commented
> The system isn't cleaning correctly the polygon coordinate list. The first time you insert the coordinates, if you insert less than 3 coordinates, the system don't allow. But if you insert correctly one polygon and after that erase one or more coordinates, you can draw a new "polygon" with less than 3 coordinates. If you try to remove this "polygon", the system breaks.
> 
> The system isn't drawing the right figure. For instance (100, 5) (200, 5) (200, 100) (100, 100) is supposed to draw a square, but it is drawed a triangle.
> 
> Some parts of the code are with spacing problems (I pointed out with comments.)

About the first problem: corrected! It was a mistake: "size() - 1" not needing "-1".

2019-04-07 17:50 UTC, ramnasidharta commented
Status: changes done. I'm not able to push them now. They will be in the remote branch until tomorrow's morning.

2019-04-08 18:33 UTC, FabioMoreiraFM approved these changes

2019-04-08 18:33 UTC, merged